services:
    mhb:
        build:
            context: .
            dockerfile: DockerfileProduction
        image: mhb
        container_name: 'mhb'
        restart: always
        ports:
            - '8119:80'
        volumes:
            - '.:/var/www/html'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
