services:
    mhb:
        build:
            context: .
            dockerfile: DockerfileLocal
        image: mhb
        container_name: 'mhb'
        #restart: always
        ports:
            - '8082:80'
            - '5173:5173'
        volumes:
            - '.:/var/www/html'
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_USERNAME=bn_myapp
            - DB_DATABASE=mhb
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - db
        networks:
            - laravel

    db:
        image: mariadb:10.11
        container_name: 'mhb_db'
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=bn_myapp
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=mhb
        ports:
            - '33006:3306'
        networks:
            - laravel
        volumes:
            - 'mariadb_data:/var/lib/mysql'

networks:
    laravel:
        driver: bridge

volumes:
    mariadb_data:
