services:
    mhb:
        build:
            context: .
            dockerfile: DockerfileProduction
        image: mhb
        container_name: 'mhb'
        restart: always
        ports:
            - '8119:80'
        volumes:
            - '.:/var/www/html'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
    queue:
        build:
            context: .
            dockerfile: DockerfileProduction
        image: mhb
        container_name: 'mhb_queue'
        restart: always
        command: php artisan queue:work --timeout=3600 --tries=3
        volumes:
            - '.:/var/www/html'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - mhb
    cron:
        image: mhb
        container_name: 'mhb_cron'
        restart: always
        command: bash -c "crontab /etc/cron.d/crontab && cron -f"
        volumes:
            - './docker/production/crontab:/etc/cron.d/crontab:ro'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        depends_on:
            - mhb
