<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('cnarh', function (Blueprint $table) {
            $table->id();
            $table->integer('int_cd_cnarh40')->nullable();
            $table->integer('int_cd_regla')->nullable();
            $table->string('int_tin_ds', 100)->nullable();
            $table->integer('int_tin_cd')->nullable();
            $table->string('int_tsu_ds', 15)->nullable();
            $table->integer('int_tsu_cd')->nullable();
            $table->integer('int_tch_cd')->nullable();
            $table->string('int_tch_ds', 30)->nullable();
            $table->string('int_tsi_ds', 30)->nullable();
            $table->integer('int_tsi_cd')->nullable();
            $table->string('int_tod_ds', 50)->nullable();
            $table->string('int_tdm_ds', 10)->nullable();
            $table->string('int_nu_cnarh', 30)->nullable();
            $table->string('int_nu_siagas', 20)->nullable();
            $table->decimal('int_nu_latitude', 12, 10)->nullable();
            $table->decimal('int_nu_longitude', 12, 10)->nullable();
            $table->string('ing_nu_ibgemunicipio', 20)->nullable();
            $table->string('ing_sg_ufmunicipio', 2)->nullable();
            $table->string('ing_nm_municipio', 255)->nullable();
            $table->string('int_nm_corpohidrico',255)->nullable();
            $table->string('int_nm_corpohidricoalterado', 255)->nullable();
            $table->string('int_ds_orgao', 30)->nullable();
            $table->date('int_dt_registro')->nullable();
            $table->string('int_cd_declaracao', 20)->nullable();
            $table->string('int_cd_origem', 20)->nullable();
            $table->string('int_ds_opcional', 255)->nullable();
            $table->string('emp_nm_empreendimento', 255)->nullable();
            $table->string('emp_nm_usuario', 255)->nullable();
            $table->string('out_tp_outorga', 255)->nullable();
            $table->integer('out_tpo_cd')->nullable();
            $table->string('out_tp_situacaooutorga', 30)->nullable();
            $table->integer('out_tsp_cd')->nullable();
            $table->date('out_dt_outorgafinal')->nullable();
            $table->date('out_dt_outorgainicial')->nullable();
            $table->string('out_nu_processo', 255)->nullable();
            $table->string('out_tp_ato', 100)->nullable();
            $table->string('out_nu_ato', 50)->nullable();
            $table->decimal('dad_qt_vazaodiajan', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiafev', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiamar', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiaabr', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiamai', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiajun', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiajul', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiaago', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiaset', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiaout', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodianov', 25,16)->nullable();
            $table->decimal('dad_qt_vazaodiadez', 25,16)->nullable();
            $table->decimal('dad_qt_horasjan', 3,1)->nullable();
            $table->decimal('dad_qt_horasfev', 3,1)->nullable();
            $table->decimal('dad_qt_horasmar', 3,1)->nullable();
            $table->decimal('dad_qt_horasabr', 3,1)->nullable();
            $table->decimal('dad_qt_horasmai', 3,1)->nullable();
            $table->decimal('dad_qt_horasjun', 3,1)->nullable();
            $table->decimal('dad_qt_horasjul', 3,1)->nullable();
            $table->decimal('dad_qt_horasago', 3,1)->nullable();
            $table->decimal('dad_qt_horasset', 3,1)->nullable();
            $table->decimal('dad_qt_horasout', 3,1)->nullable();
            $table->decimal('dad_qt_horasnov', 3,1)->nullable();
            $table->decimal('dad_qt_horasdez', 3,1)->nullable();
            $table->integer('dad_qt_diajan')->nullable();
            $table->integer('dad_qt_diafev')->nullable();
            $table->integer('dad_qt_diamar')->nullable();
            $table->integer('dad_qt_diaabr')->nullable();
            $table->integer('dad_qt_diamai')->nullable();
            $table->integer('dad_qt_diajun')->nullable();
            $table->integer('dad_qt_diajul')->nullable();
            $table->integer('dad_qt_diaago')->nullable();
            $table->integer('dad_qt_diaset')->nullable();
            $table->integer('dad_qt_diaout')->nullable();
            $table->integer('dad_qt_dianov')->nullable();
            $table->integer('dad_qt_diadez')->nullable();
            $table->decimal('int_qt_vazaomaxima', 25,16)->nullable();
            $table->decimal('int_qt_vazaomedia', 25,16)->nullable();
            $table->decimal('int_qt_volumeanual', 25,16)->nullable();
            $table->string('fin_tfn_ds', 255)->nullable();
            $table->integer('fin_tfn_cd')->nullable();
            $table->decimal('fes_nu_profundidademediatanque', 25,16)->nullable();
            $table->decimal('fes_nu_areatotaltanque', 25,16)->nullable();
            $table->string('ttc_tcu_ds', 50)->nullable();
            $table->decimal('ttc_tcu_cd', 25,16)->nullable();
            $table->string('fse_tes_ds',100)->nullable();
            $table->integer('fse_tes_cd')->nullable();
            $table->string('fie_nu_populacaofinalatendida', 20)->nullable();
            $table->string('fie_tps_ds' ,100)->nullable();
            $table->integer('fie_tps_cd')->nullable(); 
            $table->string('fah_tah_ds', 100)->nullable();
            $table->integer('fah_tah_cd')->nullable(); 
            $table->decimal('fah_nu_potenciainstalada', 25,16)->nullable();
            $table->boolean('fah_ic_aproveitamentofiodagua')->nullable();
            $table->decimal('fah_nu_areainundadana', 25,16)->nullable();
            $table->decimal('fah_nu_volumena', 25,16)->nullable();
            $table->string('fpe_tpe_ds', 30)->nullable();
            $table->integer('fpe_tpe_cd')->nullable();
            $table->integer('fpe_cna_cd')->nullable();
            $table->decimal('ius_nu_alturares', 25,16)->nullable();
            $table->decimal('ius_nu_arearesmax', 25,16)->nullable();
            $table->decimal('ius_nu_volumeres', 25,16)->nullable();
            $table->decimal('ius_nu_coeficiente_retorno', 25,16)->nullable();
            $table->string('ius_nm_entidadeconcedente', 255)->nullable();
            $table->string('ius_nu_concessao', 100)->nullable();
            $table->date('ius_dt_finalconcessao')->nullable();
            $table->string('etp_mpe_ds', 20)->nullable();
            $table->string('etp_mpe_cd', 20)->nullable();
            $table->string('etp_nu_quantidademaxmensal', 20)->nullable();
            $table->string('sir_tsi_ds', 50)->nullable();
            $table->integer('sir_tsi_cd')->nullable();
            $table->string('sir_tct_ds', 100)->nullable();
            $table->integer('sir_tct_cd')->nullable();
            $table->decimal('sir_nu_areairrigada', 25,16)->nullable();
            $table->integer('fia_nu_populacaoatendida')->nullable();
            $table->string('fte_nu_potenciainstalada', 20)->nullable();
            $table->string('fte_nu_producaomensalmedia', 20)->nullable();
            $table->string('fte_tco_ds', 20)->nullable();
            $table->string('fte_tco_cd', 20)->nullable();
            $table->string('fte_tsr_cd', 20)->nullable();
            $table->string('pme_cd_mesoperacao', 20)->nullable();
            $table->string('pme_nu_producaomensal', 20)->nullable();
            $table->string('fea_nu_producaomaxmensalareia', 20)->nullable();
            $table->integer('fea_nu_proporcaoaguapolpa')->nullable();
            $table->string('fea_pc_teorumidade', 20)->nullable();
            $table->string('foh_toh_ds', 100)->nullable();
            $table->integer('foh_toh_cd')->nullable();
            $table->decimal('fre_nu_areainundadana', 25,16)->nullable();
            $table->decimal('fre_nu_volumena', 25,16)->nullable();
            $table->string('fou_tou_ds', 100)->nullable();
            $table->integer('fou_tou_cd')->nullable();
            $table->integer('hte_nu_quantidade')->nullable();
            $table->string('tuc_tec_ds', 50)->nullable();
            $table->integer('tuc_tec_cd')->nullable();
            $table->string('tuc_ds', 20)->nullable();
            $table->integer('tuc_cd')->nullable();
            $table->decimal('ftr_ar_totalempreendimento', 25,16)->nullable();
            $table->string('ftr_nu_processompa', 20)->nullable();
            $table->integer('esc_nu_producaopretendida')->nullable();
            $table->string('esc_tet_ds', 20)->nullable();
            $table->integer('esc_tet_cd')->nullable();
            $table->string('cte_tsc_ds', 20)->nullable();
            $table->integer('cte_tsc_cd')->nullable();
            $table->string('cte_tca_ds', 20)->nullable();
            $table->integer('cte_tca_cd')->nullable();
            $table->integer('cte_nu_cabecas')->nullable();
            $table->decimal('efl_nu_dbobruto', 25,16)->nullable();
            $table->decimal('efl_nu_dbotratado', 25,16)->nullable();
            $table->decimal('efl_nu_fosforobruto', 25,16)->nullable();
            $table->decimal('efl_nu_fosforotratado', 25,16)->nullable();
            $table->decimal('efl_nu_nitrogeniobruto', 25,16)->nullable();
            $table->decimal('efl_nu_nitrogeniotratado', 25,16)->nullable();
            $table->decimal('efl_nu_temperatura', 25,16)->nullable();
            $table->string('efl_tte_ds', 100)->nullable();
            $table->integer('efl_tte_cd')->nullable();
            $table->string('itc_tum_ds', 20)->nullable();
            $table->integer('itc_tum_cd')->nullable();
            $table->integer('itc_nu_producaoanual')->nullable();
            $table->string('cna_ds', 100)->nullable();
            $table->string('cna_cd_cnae', 20)->nullable();
            $table->date('asb_dt_instalacao')->nullable();
            $table->string('asb_tnp_ds', 50)->nullable();
            $table->integer('asb_tnp_cd')->nullable();
            $table->decimal('asb_nu_diametroperfuracao', 25,16)->nullable();
            $table->decimal('asb_nu_diametrofiltro', 25,16)->nullable();
            $table->string('asb_aqp_ds', 20)->nullable();
            $table->integer('asb_aqp_cd')->nullable();
            $table->integer('asb_nu_topo')->nullable();
            $table->decimal('asb_nu_base', 25,16)->nullable();
            $table->string('asb_tpn_ds', 20)->nullable();
            $table->integer('asb_tpn_cd')->nullable();
            $table->string('abs_tca_ds', 20)->nullable();
            $table->integer('abs_tca_cd')->nullable();
            $table->decimal('asb_nu_profundidadefinal', 25,16)->nullable();
            $table->decimal('asb_nu_alturabocatubo', 25,16)->nullable();
            $table->integer('asb_nu_cotaterreno')->nullable();
            $table->string('tst_dt', 20)->nullable();
            $table->string('tst_ttb_ds', 50)->nullable();
            $table->integer('tst_ttb_cd')->nullable();
            $table->integer('tst_ds_tempoduracao')->nullable();
            $table->decimal('tst_nu_nd', 25,16)->nullable();
            $table->decimal('tst_nu_ne', 25,16)->nullable();
            $table->decimal('tst_vz_estabilizacao', 25,16)->nullable();
            $table->string('tst_tmi_ds')->nullable();
            $table->integer('tst_tmi_cd')->nullable();
            $table->string('tst_nu_coeficientearmazenamento', 20)->nullable();
            $table->string('tst_nu_transmissividade', 20)->nullable();
            $table->string('tst_nu_condutividadehidraulica', 20)->nullable();
            $table->integer('tst_nu_permeabilidade')->nullable();
            $table->date('ama_dt_coleta')->nullable();
            $table->date('ama_dt_analise')->nullable();
            $table->decimal('ama_nu_condutividadeeletrica', 25,16)->nullable();
            $table->decimal('ama_qt_temperatura', 25,16)->nullable();
            $table->decimal('ama_qt_std', 25,16)->nullable();
            $table->decimal('ama_qt_ph', 25,16)->nullable();
            $table->decimal('ama_qt_coliformestotais', 25,16)->nullable();
            $table->integer('ama_qt_coliformesfecais')->nullable();
            $table->decimal('ama_qt_bicarbonato', 25,16)->nullable();
            $table->decimal('ama_qt_calcio', 25,16)->nullable();
            $table->decimal('ama_qt_carbonato', 25,16)->nullable();
            $table->decimal('ama_qt_cloreto', 25,16)->nullable();
            $table->decimal('ama_qt_durezatotal', 25,16)->nullable();
            $table->decimal('ama_qt_ferrototal', 25,16)->nullable();
            $table->decimal('ama_qt_fluoretos', 25,16)->nullable();
            $table->decimal('ama_qt_nitratos', 25,16)->nullable();
            $table->decimal('ama_qt_nitritos', 25,16)->nullable();
            $table->decimal('ama_qt_potassio', 25,16)->nullable();
            $table->decimal('ama_qt_sodio', 25,16)->nullable();
            $table->decimal('ama_qt_sulfato', 25,16)->nullable();
            $table->decimal('ama_qt_magnesio', 25,16)->nullable();
            $table->dateTime('data_extracao')->nullable();
            $table->integer('ing_cd_ottobacia_trecho')->nullable();
            $table->integer('ing_cd_comitefederal')->nullable();
            $table->string('ing_nm_comitefederal', 100)->nullable();
            $table->integer('ing_cd_comiteestadual')->nullable();
            $table->string('ing_nm_comiteestadual', 100)->nullable();
            $table->integer('ing_cs_conama')->nullable();
            $table->string('oto_nm_outrouso', 100)->nullable();
            $table->string('oto_ds_outrouso', 500)->nullable();
            $table->decimal('fir_nu_areatotalirrigada', 25,16)->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('cnarh');
    }
};
