<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        // Tabela principal das camadas
        Schema::create('map_layers', function (Blueprint $table) {
            $table->id();
            $table->string('slug', 100)->unique();
            $table->string('name', 255);
            $table->enum('type', ['tile', 'geojson']);
            $table->enum('source_type', ['polygon', 'point'])->default('polygon');
            $table->boolean('is_active')->default(true);
            $table->boolean('has_legend')->default(false);
            $table->integer('display_order')->default(0);
            $table->string('attribution', 255)->nullable();
            $table->integer('min_zoom')->default(5);
            $table->integer('max_zoom')->default(12);
            $table->decimal('opacity', 3, 2)->default(0.60);
            $table->boolean('tms')->default(true);
            $table->string('path_zip',255)->nullable();
            $table->string('url_pattern', 500);
            $table->string('marker_color', 20)->nullable();
            $table->integer('marker_radius')->nullable();
            $table->string('field_name', 100)->nullable();
            $table->boolean('single_color')->default(false);
            $table->boolean('borders_only')->default(false);
            $table->boolean('draw_borders')->default(false);
            $table->string('border_color', 20)->nullable();
            $table->integer('border_buffer')->nullable();
            $table->text('palette_text')->nullable();
            $table->json('sql_mapping_json')->nullable();
            $table->timestamps();
        });

        // Tabela de legendas
        Schema::create('map_layer_legends', function (Blueprint $table) {
            $table->id();
            $table->foreignId('map_layer_id')->constrained('map_layers')->onDelete('cascade');
            $table->string('label', 255);
            $table->string('color_hex', 7);
            $table->integer('display_order')->default(0);
            $table->timestamps();
        });

        // ============================================
        // INSERT DOS DADOS
        // ============================================
        
        $now = now();

        DB::table('map_layers')->insert([
            // 1. Aquíferos
            [
                'slug' => 'aquiferos_bahia',
                'name' => 'Aquíferos (UFBA/INGA 2009)',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => true,
                'display_order' => 1,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.60,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/aquiferos_inga_ufba_2009.zip',
                'url_pattern' => '/tiles/aquiferos_bahia/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => 'classe',
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => '50,50,50',
                'border_buffer' => 500,
                'sql_mapping_json' => json_encode(['Metasedimentar' => 1, 'Cristalino' => 2, 'Cárstico' => 3, 'Granular' => 4]),
                'palette_text' => "0 0 0 0 0\n1 171 205 78 255\n2 217 144 101 255\n3 91 175 178 255\n4 199 172 15 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 2. BA UF IBGE
            [
                'slug' => 'ba_uf_ibge_2019',
                'name' => 'BA UF IBGE 2019',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 2,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.60,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/ba_uf_ibge_2019.zip',
                'url_pattern' => '/tiles/ba_uf_ibge_2019/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => null,
                'single_color' => true,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => "0 0 0 0 0\n1 120 200 130 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 3. Bacias N4
            [
                'slug' => 'bacias_n4',
                'name' => 'Bacias Hidrográficas N4',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 3,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.50,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/Bacias_hidrograficas_n4.zip',
                'url_pattern' => '/tiles/bacias_n4/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => null,
                'single_color' => true,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => "0 0 0 0 0\n1 180 180 180 255\n9 0 0 0 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 4. Biomas
            [
                'slug' => 'biomas_bahia',
                'name' => 'Biomas',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => true,
                'display_order' => 4,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.60,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/biomas_ibge_2019_ajust.zip',
                'url_pattern' => '/tiles/biomas_bahia/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => 'bioma',
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => false,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => json_encode(['Caatinga' => 1, 'Cerrado' => 2, 'Mata Atlântica' => 3]),
                'palette_text' => "0 0 0 0 0\n1 208 183 44 255\n2 206 234 123 255\n3 116 212 112 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 5. Estações Hidrológicas (GeoJSON)
            [
                'slug' => 'estacoes_hidrologicas',
                'name' => 'Estações Hidrológicas',
                'type' => 'geojson',
                'source_type' => 'point',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 5,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 18,
                'opacity' => 0.80,
                'tms' => false,
                'path_zip' => 'storage/app/shapefiles/estacoes_hidrologicas.zip',
                'url_pattern' => '/geojson/estacoes_hidrologicas.geojson',
                'marker_color' => '#ff6600',
                'marker_radius' => 6,
                'field_name' => null,
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => false,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 6. Estações Meteorológicas (GeoJSON)
            [
                'slug' => 'estacoes_meteorologicas',
                'name' => 'Estações Meteorológicas',
                'type' => 'geojson',
                'source_type' => 'point',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 6,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 18,
                'opacity' => 0.80,
                'tms' => false,
                'path_zip' => 'storage/app/shapefiles/estacoes_meteorologicas.zip',
                'url_pattern' => '/geojson/estacoes_meteorologicas.geojson',
                'marker_color' => '#0066ff',
                'marker_radius' => 6,
                'field_name' => null,
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => false,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 7. Geologia 2004
            [
                'slug' => 'geologia_2004',
                'name' => 'Geologia 2004',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => true,
                'display_order' => 7,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 1.00,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/geologia_2004.zip',
                'url_pattern' => '/tiles/geologia_2004/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => 'subclasse1',
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => '50,50,50',
                'border_buffer' => 500,
                'sql_mapping_json' => json_encode([
                    'Clastica' => 1, 'Clastica, Clasto-quimica' => 2, 'Clastica, Clasto-quimica, Quimica' => 3,
                    'Clastica, Metamorfismo regional' => 4, 'Clastica, Quimica' => 5, 'Clastica, Quimica, Clasto-quimica' => 6,
                    'Clastica, Quimica, Metamorfismo regional' => 7, 'Clasto-quimica, Clastica' => 8, 'Clasto-quimica, Clastica, Quimica' => 9,
                    'Metamorfismo Dinamico, Metamorfismo regional' => 10, 'Metamorfismo regional' => 11, 'Metamorfismo regional, Clastica' => 12,
                    'Metamorfismo regional, Plutonica' => 13, 'Metamorfismo regional, Plutonica, Metamorfismo Dinamico' => 14,
                    'Metamorfismo regional, Quimica' => 15, 'Metamorfismo regional, Vulcanica' => 16, 'Metamorfismo regional, Vulcanoclastica' => 17,
                    'Plutonica' => 18, 'Plutonica, Metamorfismo regional' => 19, 'Quimica' => 20, 'Quimica, Clastica' => 21,
                    'Quimica, Metamorfismo regional' => 22, 'Quimica, Metamorfismo regional, Clastica' => 23,
                    'Quimica, Metamorfismo regional, Vulcanica' => 24, 'Sedimentos inconsolidados' => 25,
                    'Sedimentos inconsolidados, Biogenica' => 26, 'Sedimentos inconsolidados, Quimica' => 27,
                    'Vulcanica' => 28, 'Vulcanica, Plutonica' => 29, 'SUBCLASSE1 is "' => 30
                ]),
                'palette_text' => "0 0 0 0 0\n1 226 234 107 255\n2 166 184 74 255\n3 231 232 159 255\n4 239 241 187 255\n5 180 163 34 255\n6 204 210 22 255\n7 238 225 104 255\n8 248 190 41 255\n9 195 135 23 255\n10 205 124 120 255\n11 172 115 108 255\n12 201 102 131 255\n13 183 97 106 255\n14 151 66 92 255\n15 134 58 73 255\n16 160 37 54 255\n17 202 52 62 255\n18 232 193 148 255\n19 217 121 57 255\n20 157 204 228 255\n21 42 184 175 255\n22 143 179 187 255\n23 31 87 137 255\n24 45 75 102 255\n25 159 140 174 255\n26 133 110 147 255\n27 106 155 111 255\n28 231 243 121 255\n29 201 168 69 255\n30 226 149 231 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 8. Geomorfologia 2004
            [
                'slug' => 'geomorfologia_2004',
                'name' => 'Geomorfologia 2004',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => true,
                'display_order' => 8,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.80,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/geomorfologia_2004.zip',
                'url_pattern' => '/tiles/geomorfologia_2004/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => 'nomeug',
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => '50,50,50',
                'border_buffer' => 500,
                'sql_mapping_json' => json_encode([
                    'Tabuleiros interioranos' => 1, 'Tabuleiros' => 2, 'Tabuleiro Costeiros e baixos platôs' => 3,
                    'Serras, alvéolos e depressões intramontana' => 4, 'Serras setentrionais da Serra geral do espinhaço' => 5,
                    'Serras marginais' => 6, 'Serras e maciços residuais' => 7, 'Região de acumulação' => 8,
                    'Plano sub-estrutural dos gerais' => 9, 'Planaltos kársticos' => 10, 'Pediplano sertanejo' => 11,
                    'Pediplano cimero da chapada diamantina' => 12, 'Pedimentos funcionais ou retocados por drenagem incipiente' => 13,
                    'Patamares marginais da Serra geral do espinhaço' => 14, 'Paramares estruturais' => 15,
                    'Paramares e serras do rio de Contas do Planalto Sul-Baiano' => 16, 'Mares de morro' => 17,
                    'Formas de dissecação e aplanamentos embutidos' => 18, 'Anticlinais aplanados e esvasiados, sinclinais suspensos, blocos' => 19
                ]),
                'palette_text' => "0 0 0 0 0\n1 233 181 25 255\n2 231 213 131 255\n3 193 144 29 255\n4 234 171 208 255\n5 167 101 132 255\n6 165 125 176 255\n7 133 76 133 255\n8 189 177 255 255\n9 112 135 112 255\n10 255 152 101 255\n11 214 170 170 255\n12 162 97 96 255\n13 246 237 176 255\n14 204 91 142 255\n15 114 178 142 255\n16 190 245 200 255\n17 137 187 195 255\n18 141 150 74 255\n19 223 192 163 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 9. Municípios SEI 2019
            [
                'slug' => 'municip_sei_2019',
                'name' => 'Municípios SEI 2019',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 9,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.80,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/municip_sei_2019.zip',
                'url_pattern' => '/tiles/municip_sei_2019/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => null,
                'single_color' => false,
                'borders_only' => true,
                'draw_borders' => false,
                'border_color' => '50,50,50',
                'border_buffer' => 1500,
                'sql_mapping_json' => null,
                'palette_text' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 10. Rede Qualidade Água (GeoJSON)
            [
                'slug' => 'rede_qualidade_dagua_2024',
                'name' => 'Rede Qualidade Água 2024',
                'type' => 'geojson',
                'source_type' => 'point',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 10,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 18,
                'opacity' => 0.80,
                'tms' => false,
                'path_zip' => 'storage/app/shapefiles/rede_qualidade_dagua_2024.zip',
                'url_pattern' => '/geojson/rede_qualidade_dagua_2024.geojson',
                'marker_color' => '#00cc66',
                'marker_radius' => 6,
                'field_name' => null,
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => false,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 11. RPPN INEMA 2023
            [
                'slug' => 'rppn_inema_2023',
                'name' => 'RPPN INEMA 2023',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 11,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.60,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/rppn_inema_2023.zip',
                'url_pattern' => '/tiles/rppn_inema_2023/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => null,
                'single_color' => true,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => "0 0 0 0 0\n1 166 237 169 255\n9 0 0 0 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 12. Solos 2004
            [
                'slug' => 'solos_2004',
                'name' => 'Solos 2004',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => true,
                'display_order' => 12,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.80,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/solos_2004.zip',
                'url_pattern' => '/tiles/solos_2004/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => 'classeperh',
                'single_color' => false,
                'borders_only' => false,
                'draw_borders' => false,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => json_encode([
                    'AFLORAMENTOS ROCHOSOS – AR' => 1, 'ARGISSOLO AMARELO Distrófico - PAd' => 2, 'ARGISSOLO VERMELHO - PVe' => 3,
                    'ARGISSOLO VERMELHO-AMARELO Distrófico - PVAd' => 4, 'ARGISSOLO VERMELHO-AMARELO Eutrófico - PVAe' => 5,
                    'CAMBISSOLO HÁPLICO Ta Eutrófico - CXve' => 6, 'CAMBISSOLO HÁPLICO Tb Distrófico - CXbd' => 7,
                    'CAMBISSOLO HÁPLICO Tb Eutrófico - CXbe' => 8, 'CHERNOSSOLO HÁPLICO - MXo' => 9, 'ESPODOSSOLO CÁRBICO - EKo' => 10,
                    'ESPODOSSOLO HIDROMÓRFICO - EKg' => 11, 'GLEISSOLO HÁPLICO - GXbd' => 12, 'GLEISSOLO HÁPLICO Eutrófico - GXbe' => 13,
                    'LATOSSOLO AMARELO Distrófico - LAd' => 14, 'LATOSSOLO VERMELHO Distrófico - LVd' => 15,
                    'LATOSSOLO VERMELHO Eutrófico - LVe' => 16, 'LATOSSOLO VERMELHO-AMARELO Distrófico - LVAd' => 17,
                    'LATOSSOLO VERMELHO-AMARELO Eutrófico - LVAe' => 18, 'LUVISSOLO CRÔMICO Órtico - TCo' => 19,
                    'NEOSSOLO FLÚVICO Tb Distrófico - RUBd' => 20, 'NEOSSOLO FLÚVICO Tb Eutrófico - RUBe' => 21,
                    'NEOSSOLO QUARTZARÊNICO - RQ' => 22, 'NEOSSOLOS LITÓLICOS - RL' => 23, 'NEOSSOLOS LITÓLICOS Distróficos - RLd' => 24,
                    'NEOSSOLOS LITÓLICOS Eutróficos - RLe' => 25, 'NEOSSOLOS REGOLÍTICOS Eutróficos - RRe' => 26,
                    'ORGANOSSOLO HÁPLICO - OX' => 27, 'PLANOSSOLO HÁPLICO Eutrófico solódico - SXen' => 28,
                    'PLANOSSOLO NÁTRICO Órtico - SNo' => 29, 'TIPOS DE TERRENO' => 30, 'VERTISSOLOS - V' => 31
                ]),
                'palette_text' => "0 0 0 0 0\n1 213 216 212 255\n2 255 237 231 255\n3 233 176 164 255\n4 244 204 197 255\n5 209 159 154 255\n6 201 189 140 255\n7 183 165 136 255\n8 179 170 134 255\n9 167 80 95 255\n10 168 184 210 255\n11 137 166 193 255\n12 180 208 231 255\n13 133 179 243 255\n14 254 247 169 255\n15 221 164 123 255\n16 234 200 157 255\n17 223 174 139 255\n18 202 140 102 255\n19 231 157 53 255\n20 239 226 211 255\n21 233 225 208 255\n22 255 253 211 255\n23 160 160 160 255\n24 123 129 126 255\n25 223 223 223 255\n26 128 129 158 255\n27 184 192 224 255\n28 173 212 163 255\n29 152 210 193 255\n30 141 155 221 255\n31 143 168 119 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 13. UC INEMA 2025
            [
                'slug' => 'uc_inema_2025',
                'name' => 'UC INEMA 2025',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 13,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.60,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/uc_inema_2025.zip',
                'url_pattern' => '/tiles/uc_inema_2025/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => null,
                'single_color' => true,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => "0 0 0 0 0\n1 100 200 120 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 14. UCs Federais Bahia 2024
            [
                'slug' => 'ucs_federais_bahia_2024_2',
                'name' => 'UCs Federais Bahia 2024',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 14,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.60,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/ucs_federais_bahia_2024_2.zip',
                'url_pattern' => '/tiles/ucs_federais_bahia_2024_2/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => null,
                'single_color' => true,
                'borders_only' => false,
                'draw_borders' => true,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => "0 0 0 0 0\n1 180 120 200 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // 15. Imóveis Rurais
            [
                'slug' => 'imovel_rural_limite_propriedade_inema',
                'name' => 'Imóveis Rurais',
                'type' => 'tile',
                'source_type' => 'polygon',
                'is_active' => true,
                'has_legend' => false,
                'display_order' => 15,
                'attribution' => '',
                'min_zoom' => 5,
                'max_zoom' => 12,
                'opacity' => 0.90,
                'tms' => true,
                'path_zip' => 'storage/app/shapefiles/Imovel_Rural_Limite_Propriedade_INEMA.zip',
                'url_pattern' => '/tiles/imovel_rural_limite_propriedade_inema/{z}/{x}/{y}.png',
                'marker_color' => null,
                'marker_radius' => null,
                'field_name' => null,
                'single_color' => true,
                'borders_only' => false,
                'draw_borders' => false,
                'border_color' => null,
                'border_buffer' => null,
                'sql_mapping_json' => null,
                'palette_text' => "0 0 0 0 0\n1 255 235 100 255\nnv 0 0 0 0",
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);

        // ============================================
        // INSERT DAS LEGENDAS
        // ============================================

        // Legendas Aquíferos (layer_id = 1)
        DB::table('map_layer_legends')->insert([
            ['map_layer_id' => 1, 'label' => 'Metasedimentar', 'color_hex' => '#ABCD4E', 'display_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 1, 'label' => 'Cristalino', 'color_hex' => '#D99065', 'display_order' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 1, 'label' => 'Cárstico', 'color_hex' => '#5BAFB2', 'display_order' => 3, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 1, 'label' => 'Granular', 'color_hex' => '#C7AC0F', 'display_order' => 4, 'created_at' => $now, 'updated_at' => $now],
        ]);

        // Legendas Biomas (layer_id = 4)
        DB::table('map_layer_legends')->insert([
            ['map_layer_id' => 4, 'label' => 'Caatinga', 'color_hex' => '#D0B72C', 'display_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 4, 'label' => 'Cerrado', 'color_hex' => '#CEEA7B', 'display_order' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 4, 'label' => 'Mata Atlântica', 'color_hex' => '#74D470', 'display_order' => 3, 'created_at' => $now, 'updated_at' => $now],
        ]);

        // Legendas Geologia (layer_id = 7)
        DB::table('map_layer_legends')->insert([
            ['map_layer_id' => 7, 'label' => 'Clástica', 'color_hex' => '#E2EA6B', 'display_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clástica, Clasto-química', 'color_hex' => '#A6B84A', 'display_order' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clástica, Clasto-química, Química', 'color_hex' => '#E7E89F', 'display_order' => 3, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clástica, Metamorfismo regional', 'color_hex' => '#EFF1BB', 'display_order' => 4, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clástica, Química', 'color_hex' => '#B4A322', 'display_order' => 5, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clástica, Química, Clasto-química', 'color_hex' => '#CCD216', 'display_order' => 6, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clástica, Química, Metamorfismo regional', 'color_hex' => '#EEE168', 'display_order' => 7, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clasto-química, Clástica', 'color_hex' => '#F8BE29', 'display_order' => 8, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Clasto-química, Clástica, Química', 'color_hex' => '#C38717', 'display_order' => 9, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo Dinâmico, Metamorfismo regional', 'color_hex' => '#CD7C78', 'display_order' => 10, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo regional', 'color_hex' => '#AC736C', 'display_order' => 11, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo regional, Clástica', 'color_hex' => '#C96683', 'display_order' => 12, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo regional, Plutônica', 'color_hex' => '#B7616A', 'display_order' => 13, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo regional, Plutônica, Metamorfismo Dinâmico', 'color_hex' => '#97425C', 'display_order' => 14, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo regional, Química', 'color_hex' => '#863A49', 'display_order' => 15, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo regional, Vulcânica', 'color_hex' => '#A02536', 'display_order' => 16, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Metamorfismo regional, Vulcanoclástica', 'color_hex' => '#CA343E', 'display_order' => 17, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Plutônica', 'color_hex' => '#E8C194', 'display_order' => 18, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Plutônica, Metamorfismo regional', 'color_hex' => '#D97939', 'display_order' => 19, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Química', 'color_hex' => '#9DCCE4', 'display_order' => 20, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Química, Clástica', 'color_hex' => '#2AB8AF', 'display_order' => 21, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Química, Metamorfismo regional', 'color_hex' => '#8FB3BB', 'display_order' => 22, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Química, Metamorfismo regional, Clástica', 'color_hex' => '#1F5789', 'display_order' => 23, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Química, Metamorfismo regional, Vulcânica', 'color_hex' => '#2D4B66', 'display_order' => 24, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Sedimentos inconsolidados', 'color_hex' => '#9F8CAE', 'display_order' => 25, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Sedimentos inconsolidados, Biogênica', 'color_hex' => '#856E93', 'display_order' => 26, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Sedimentos inconsolidados, Química', 'color_hex' => '#6A9B6F', 'display_order' => 27, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Vulcânica', 'color_hex' => '#E7F379', 'display_order' => 28, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Vulcânica, Plutônica', 'color_hex' => '#C9A845', 'display_order' => 29, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 7, 'label' => 'Não classificado', 'color_hex' => '#E295E7', 'display_order' => 30, 'created_at' => $now, 'updated_at' => $now],
        ]);

        // Legendas Geomorfologia (layer_id = 8)
        DB::table('map_layer_legends')->insert([
            ['map_layer_id' => 8, 'label' => 'Tabuleiros interioranos', 'color_hex' => '#E9B519', 'display_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Tabuleiros', 'color_hex' => '#E7D583', 'display_order' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Tabuleiro Costeiros e baixos platôs', 'color_hex' => '#C1901D', 'display_order' => 3, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Serras, alvéolos e depressões intramontana', 'color_hex' => '#EAABD0', 'display_order' => 4, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Serras setentrionais da Serra geral do espinhaço', 'color_hex' => '#A76584', 'display_order' => 5, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Serras marginais', 'color_hex' => '#A57DB0', 'display_order' => 6, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Serras e maciços residuais', 'color_hex' => '#854C85', 'display_order' => 7, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Região de acumulação', 'color_hex' => '#BDB1FF', 'display_order' => 8, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Plano sub-estrutural dos gerais', 'color_hex' => '#708770', 'display_order' => 9, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Planaltos kársticos', 'color_hex' => '#FF9865', 'display_order' => 10, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Pediplano sertanejo', 'color_hex' => '#D6AAAA', 'display_order' => 11, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Pediplano cimero da chapada diamantina', 'color_hex' => '#A26160', 'display_order' => 12, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Pedimentos funcionais ou retocados por drenagem incipiente', 'color_hex' => '#F6EDB0', 'display_order' => 13, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Patamares marginais da Serra geral do espinhaço', 'color_hex' => '#CC5B8E', 'display_order' => 14, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Patamares estruturais', 'color_hex' => '#72B28E', 'display_order' => 15, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Patamares e serras do rio de Contas do Planalto Sul-Baiano', 'color_hex' => '#BEF5C8', 'display_order' => 16, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Mares de morro', 'color_hex' => '#89BBC3', 'display_order' => 17, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Formas de dissecação e aplanamentos embutidos', 'color_hex' => '#8D964A', 'display_order' => 18, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 8, 'label' => 'Anticlinais aplanados e esvasiados, sinclinais suspensos, blocos', 'color_hex' => '#DFC0A3', 'display_order' => 19, 'created_at' => $now, 'updated_at' => $now],
        ]);

        // Legendas Solos (layer_id = 12)
        DB::table('map_layer_legends')->insert([
            ['map_layer_id' => 12, 'label' => 'Afloramentos Rochosos – AR', 'color_hex' => '#D5D8D4', 'display_order' => 1, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Argissolo Amarelo Distrófico - PAd', 'color_hex' => '#FFEDE7', 'display_order' => 2, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Argissolo Vermelho - PVe', 'color_hex' => '#E9B0A4', 'display_order' => 3, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Argissolo Vermelho-Amarelo Distrófico - PVAd', 'color_hex' => '#F4CCC5', 'display_order' => 4, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Argissolo Vermelho-Amarelo Eutrófico - PVAe', 'color_hex' => '#D19F9A', 'display_order' => 5, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Cambissolo Háplico Ta Eutrófico - CXve', 'color_hex' => '#C9BD8C', 'display_order' => 6, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Cambissolo Háplico Tb Distrófico - CXbd', 'color_hex' => '#B7A588', 'display_order' => 7, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Cambissolo Háplico Tb Eutrófico - CXbe', 'color_hex' => '#B3AA86', 'display_order' => 8, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Chernossolo Háplico - MXo', 'color_hex' => '#A7505F', 'display_order' => 9, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Espodossolo Cárbico - EKo', 'color_hex' => '#A8B8D2', 'display_order' => 10, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Espodossolo Hidromórfico - EKg', 'color_hex' => '#89A6C1', 'display_order' => 11, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Gleissolo Háplico - GXbd', 'color_hex' => '#B4D0E7', 'display_order' => 12, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Gleissolo Háplico Eutrófico - GXbe', 'color_hex' => '#85B3F3', 'display_order' => 13, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Latossolo Amarelo Distrófico - LAd', 'color_hex' => '#FEF7A9', 'display_order' => 14, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Latossolo Vermelho Distrófico - LVd', 'color_hex' => '#DDA47B', 'display_order' => 15, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Latossolo Vermelho Eutrófico - LVe', 'color_hex' => '#EAC89D', 'display_order' => 16, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Latossolo Vermelho-Amarelo Distrófico - LVAd', 'color_hex' => '#DFAE8B', 'display_order' => 17, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Latossolo Vermelho-Amarelo Eutrófico - LVAe', 'color_hex' => '#CA8C66', 'display_order' => 18, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Luvissolo Crômico Órtico - TCo', 'color_hex' => '#E79D35', 'display_order' => 19, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Neossolo Flúvico Tb Distrófico - RUBd', 'color_hex' => '#EFE2D3', 'display_order' => 20, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Neossolo Flúvico Tb Eutrófico - RUBe', 'color_hex' => '#E9E1D0', 'display_order' => 21, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Neossolo Quartzarênico - RQ', 'color_hex' => '#FFFDD3', 'display_order' => 22, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Neossolos Litólicos - RL', 'color_hex' => '#A0A0A0', 'display_order' => 23, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Neossolos Litólicos Distróficos - RLd', 'color_hex' => '#7B817E', 'display_order' => 24, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Neossolos Litólicos Eutróficos - RLe', 'color_hex' => '#DFDFDF', 'display_order' => 25, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Neossolos Regolíticos Eutróficos - RRe', 'color_hex' => '#80819E', 'display_order' => 26, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Organossolo Háplico - OX', 'color_hex' => '#B8C0E0', 'display_order' => 27, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Planossolo Háplico Eutrófico solódico - SXen', 'color_hex' => '#ADD4A3', 'display_order' => 28, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Planossolo Nátrico Órtico - SNo', 'color_hex' => '#98D2C1', 'display_order' => 29, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Tipos de Terreno', 'color_hex' => '#8D9BDD', 'display_order' => 30, 'created_at' => $now, 'updated_at' => $now],
            ['map_layer_id' => 12, 'label' => 'Vertissolos - V', 'color_hex' => '#8FA877', 'display_order' => 31, 'created_at' => $now, 'updated_at' => $now],
        ]);

    }

    public function down(): void
    {
        Schema::dropIfExists('map_layer_legends');
        Schema::dropIfExists('map_layers');
    }
};
