<?php

namespace App\Http\Resources\Public;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class CnarhDetailResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'cd_cnarh40'            => $this->int_cd_cnarh40,
            'tin_ds'                => $this->int_tin_ds,
            'tin_cd'                => $this->int_tin_cd,
            'tsu_ds'                => $this->int_tsu_ds,
            'tsu_cd'                => $this->int_tsu_cd,
            'tch_cd'                => $this->int_tch_cd,
            'tch_ds'                => $this->int_tch_ds,
            'tsi_ds'                => $this->int_tsi_ds,
            'tsi_cd'                => $this->int_tsi_cd,
            'tod_ds'                => $this->int_tod_ds,
            'tdm_ds'                => $this->int_tdm_ds,
            'nu_latitude'           => $this->int_nu_latitude,
            'nu_longitude'          => $this->int_nu_longitude,
            'nu_ibgemunicipio'      => $this->ing_nu_ibgemunicipio,
            'sg_ufmunicipio'        => $this->ing_sg_ufmunicipio,
            'nm_municipio'          => $this->ing_nm_municipio,
            'nm_corpohidrico'       => $this->int_nm_corpohidrico,
            'ds_orgao'              => $this->int_ds_orgao,
            'dt_registro'           => $this->int_dt_registro,
            'nm_empreendimento'     => $this->emp_nm_empreendimento,
            'nm_usuario'            => $this->emp_nm_usuario,
            'tp_outorga'            => $this->out_tp_outorga,
            'tpo_cd'                => $this->out_tpo_cd,
            'tp_situacaooutorga'    => $this->out_tp_situacaooutorga,
            'tsp_cd'                => $this->out_tsp_cd,
            'dt_outorgafinal'       => $this->out_dt_outorgafinal,
            'dt_outorgainicial'     => $this->out_dt_outorgainicial,
            'nu_processo'           => $this->out_nu_processo,
            'tp_ato'                => $this->out_tp_ato,
            'nu_ato'                => $this->out_nu_ato,
            'qt_vazaodiajan'        => $this->dad_qt_vazaodiajan,
            'qt_vazaodiafev'        => $this->dad_qt_vazaodiafev,
            'qt_vazaodiamar'        => $this->dad_qt_vazaodiamar,
            'qt_vazaodiaabr'        => $this->dad_qt_vazaodiaabr,
            'qt_vazaodiamai'        => $this->dad_qt_vazaodiamai,
            'qt_vazaodiajun'        => $this->dad_qt_vazaodiajun,
            'qt_vazaodiajul'        => $this->dad_qt_vazaodiajul,
            'qt_vazaodiaago'        => $this->dad_qt_vazaodiaago,
            'qt_vazaodiaset'        => $this->dad_qt_vazaodiaset,
            'qt_vazaodiaout'        => $this->dad_qt_vazaodiaout,
            'qt_vazaodianov'        => $this->dad_qt_vazaodianov,
            'qt_vazaodiadez'        => $this->dad_qt_vazaodiadez,
            'qt_horasjan'           => $this->dad_qt_horasjan,
            'qt_horasfev'           => $this->dad_qt_horasfev,
            'qt_horasmar'           => $this->dad_qt_horasmar,
            'qt_horasabr'           => $this->dad_qt_horasabr,
            'qt_horasmai'           => $this->dad_qt_horasmai,
            'qt_horasjun'           => $this->dad_qt_horasjun,
            'qt_horasjul'           => $this->dad_qt_horasjul,
            'qt_horasago'           => $this->dad_qt_horasago,
            'qt_horasset'           => $this->dad_qt_horasset,
            'qt_horasout'           => $this->dad_qt_horasout,
            'qt_horasnov'           => $this->dad_qt_horasnov,
            'qt_horasdez'           => $this->dad_qt_horasdez,
            'qt_diajan'             => $this->dad_qt_diajan,
            'qt_diafev'             => $this->dad_qt_diafev,
            'qt_diamar'             => $this->dad_qt_diamar,
            'qt_diaabr'             => $this->dad_qt_diaabr,
            'qt_diamai'             => $this->dad_qt_diamai,
            'qt_diajun'             => $this->dad_qt_diajun,
            'qt_diajul'             => $this->dad_qt_diajul,
            'qt_diaago'             => $this->dad_qt_diaago,
            'qt_diaset'             => $this->dad_qt_diaset,
            'qt_diaout'             => $this->dad_qt_diaout,
            'qt_dianov'             => $this->dad_qt_dianov,
            'qt_diadez'             => $this->dad_qt_diadez,
            'qt_vazaomaxima'        => $this->int_qt_vazaomaxima,
            'qt_vazaomedia'         => $this->int_qt_vazaomedia,
            'qt_volumeanual'        => $this->int_qt_volumeanual,
            'tfn_ds'                => $this->fin_tfn_ds,
            'tfn_cd'                => $this->fin_tfn_cd,
            'nu_populacaoatendida'  => $this->fia_nu_populacaoatendida,
            'data_extracao'         => $this->data_extracao,
            'cd_ottobacia_trecho'   => $this->ing_cd_ottobacia_trecho,
            'cd_comitefederal'      => $this->ing_cd_comitefederal,
            'nm_comitefederal'      => $this->ing_nm_comitefederal,
            'cd_comiteestadual'     => $this->ing_cd_comiteestadual,
            'nm_comiteestadual'     => $this->ing_nm_comiteestadual,
        ];
    }
}
