<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cnarh extends Model
{
    use SoftDeletes;

    protected $table = 'cnarh';

    protected $fillable = [
        'int_cd_cnarh40',
        'int_cd_regla',
        'int_tin_ds',
        'int_tin_cd',
        'int_tsu_ds',
        'int_tsu_cd',
        'int_tch_cd',
        'int_tch_ds',
        'int_tsi_ds',
        'int_tsi_cd',
        'int_tod_ds',
        'int_tdm_ds',
        'int_nu_cnarh',
        'int_nu_siagas',
        'int_nu_latitude',
        'int_nu_longitude',
        'ing_nu_ibgemunicipio',
        'ing_sg_ufmunicipio',
        'ing_nm_municipio',
        'int_nm_corpohidrico',
        'int_nm_corpohidricoalterado',
        'int_ds_orgao',
        'int_dt_registro',
        'int_cd_declaracao',
        'int_cd_origem',
        'int_ds_opcional',
        'emp_nm_empreendimento',
        'emp_nm_usuario',
        'out_tp_outorga',
        'out_tpo_cd',
        'out_tp_situacaooutorga',
        'out_tsp_cd',
        'out_dt_outorgafinal',
        'out_dt_outorgainicial',
        'out_nu_processo',
        'out_tp_ato',
        'out_nu_ato',
        'dad_qt_vazaodiajan',
        'dad_qt_vazaodiafev',
        'dad_qt_vazaodiamar',
        'dad_qt_vazaodiaabr',
        'dad_qt_vazaodiamai',
        'dad_qt_vazaodiajun',
        'dad_qt_vazaodiajul',
        'dad_qt_vazaodiaago',
        'dad_qt_vazaodiaset',
        'dad_qt_vazaodiaout',
        'dad_qt_vazaodianov',
        'dad_qt_vazaodiadez',
        'dad_qt_horasjan',
        'dad_qt_horasfev',
        'dad_qt_horasmar',
        'dad_qt_horasabr',
        'dad_qt_horasmai',
        'dad_qt_horasjun',
        'dad_qt_horasjul',
        'dad_qt_horasago',
        'dad_qt_horasset',
        'dad_qt_horasout',
        'dad_qt_horasnov',
        'dad_qt_horasdez',
        'dad_qt_diajan',
        'dad_qt_diafev',
        'dad_qt_diamar',
        'dad_qt_diaabr',
        'dad_qt_diamai',
        'dad_qt_diajun',
        'dad_qt_diajul',
        'dad_qt_diaago',
        'dad_qt_diaset',
        'dad_qt_diaout',
        'dad_qt_dianov',
        'dad_qt_diadez',
        'int_qt_vazaomaxima',
        'int_qt_vazaomedia',
        'int_qt_volumeanual',
        'fin_tfn_ds',
        'fin_tfn_cd',
        'fes_nu_profundidademediatanque',
        'fes_nu_areatotaltanque',
        'ttc_tcu_ds',
        'ttc_tcu_cd',
        'fse_tes_ds',
        'fse_tes_cd',
        'fie_nu_populacaofinalatendida',
        'fie_tps_ds',
        'fie_tps_cd',
        'fah_tah_ds',
        'fah_tah_cd',
        'fah_nu_potenciainstalada',
        'fah_ic_aproveitamentofiodagua',
        'fah_nu_areainundadana',
        'fah_nu_volumena',
        'fpe_tpe_ds',
        'fpe_tpe_cd',
        'fpe_cna_cd',
        'ius_nu_alturares',
        'ius_nu_arearesmax',
        'ius_nu_volumeres',
        'ius_nu_coeficiente_retorno',
        'ius_nm_entidadeconcedente',
        'ius_nu_concessao',
        'ius_dt_finalconcessao',
        'etp_mpe_ds',
        'etp_mpe_cd',
        'etp_nu_quantidademaxmensal',
        'sir_tsi_ds',
        'sir_tsi_cd',
        'sir_tct_ds',
        'sir_tct_cd',
        'sir_nu_areairrigada',
        'fia_nu_populacaoatendida',
        'fte_nu_potenciainstalada',
        'fte_nu_producaomensalmedia',
        'fte_tco_ds',
        'fte_tco_cd',
        'fte_tsr_cd',
        'pme_cd_mesoperacao',
        'pme_nu_producaomensal',
        'fea_nu_producaomaxmensalareia',
        'fea_nu_proporcaoaguapolpa',
        'fea_pc_teorumidade',
        'foh_toh_ds',
        'foh_toh_cd',
        'fre_nu_areainundadana',
        'fre_nu_volumena',
        'fou_tou_ds',
        'fou_tou_cd',
        'hte_nu_quantidade',
        'tuc_tec_ds',
        'tuc_tec_cd',
        'tuc_ds',
        'tuc_cd',
        'ftr_ar_totalempreendimento',
        'ftr_nu_processompa',
        'esc_nu_producaopretendida',
        'esc_tet_ds',
        'esc_tet_cd',
        'cte_tsc_ds',
        'cte_tsc_cd',
        'cte_tca_ds',
        'cte_tca_cd',
        'cte_nu_cabecas',
        'efl_nu_dbobruto',
        'efl_nu_dbotratado',
        'efl_nu_fosforobruto',
        'efl_nu_fosforotratado',
        'efl_nu_nitrogeniobruto',
        'efl_nu_nitrogeniotratado',
        'efl_nu_temperatura',
        'efl_tte_ds',
        'efl_tte_cd',
        'itc_tum_ds',
        'itc_tum_cd',
        'itc_nu_producaoanual',
        'cna_ds',
        'cna_cd_cnae',
        'asb_dt_instalacao',
        'asb_tnp_ds',
        'asb_tnp_cd',
        'asb_nu_diametroperfuracao',
        'asb_nu_diametrofiltro',
        'asb_aqp_ds',
        'asb_aqp_cd',
        'asb_nu_topo',
        'asb_nu_base',
        'asb_tpn_ds',
        'asb_tpn_cd',
        'abs_tca_ds',
        'abs_tca_cd',
        'asb_nu_profundidadefinal',
        'asb_nu_alturabocatubo',
        'asb_nu_cotaterreno',
        'tst_dt',
        'tst_ttb_ds',
        'tst_ttb_cd',
        'tst_ds_tempoduracao',
        'tst_nu_nd',
        'tst_nu_ne',
        'tst_vz_estabilizacao',
        'tst_tmi_ds',
        'tst_tmi_cd',
        'tst_nu_coeficientearmazenamento',
        'tst_nu_transmissividade',
        'tst_nu_condutividadehidraulica',
        'tst_nu_permeabilidade',
        'ama_dt_coleta',
        'ama_dt_analise',
        'ama_nu_condutividadeeletrica',
        'ama_qt_temperatura',
        'ama_qt_std',
        'ama_qt_ph',
        'ama_qt_coliformestotais',
        'ama_qt_coliformesfecais',
        'ama_qt_bicarbonato',
        'ama_qt_calcio',
        'ama_qt_carbonato',
        'ama_qt_cloreto',
        'ama_qt_durezatotal',
        'ama_qt_ferrototal',
        'ama_qt_fluoretos',
        'ama_qt_nitratos',
        'ama_qt_nitritos',
        'ama_qt_potassio',
        'ama_qt_sodio',
        'ama_qt_sulfato',
        'ama_qt_magnesio',
        'data_extracao',
        'ing_cd_ottobacia_trecho',
        'ing_cd_comitefederal',
        'ing_nm_comitefederal',
        'ing_cd_comiteestadual',
        'ing_nm_comiteestadual',
        'ing_cs_conama',
        'oto_nm_outrouso',
        'oto_ds_outrouso',
        'fir_nu_areatotalirrigada',
    ];

    protected $casts = [
        'int_cd_cnarh40' => 'integer',
        'int_cd_regla' => 'integer',
        'int_tin_cd' => 'integer',
        'int_tsu_cd' => 'integer',
        'int_tch_cd' => 'integer',
        'int_tsi_cd' => 'integer',
        'int_nu_latitude' => 'decimal:10',
        'int_nu_longitude' => 'decimal:10',
        'int_dt_registro' => 'date',
        'out_tpo_cd' => 'integer',
        'out_tsp_cd' => 'integer',
        'out_dt_outorgafinal' => 'date',
        'out_dt_outorgainicial' => 'date',
        'dad_qt_vazaodiajan' => 'decimal:16',
        'dad_qt_vazaodiafev' => 'decimal:16',
        'dad_qt_vazaodiamar' => 'decimal:16',
        'dad_qt_vazaodiaabr' => 'decimal:16',
        'dad_qt_vazaodiamai' => 'decimal:16',
        'dad_qt_vazaodiajun' => 'decimal:16',
        'dad_qt_vazaodiajul' => 'decimal:16',
        'dad_qt_vazaodiaago' => 'decimal:16',
        'dad_qt_vazaodiaset' => 'decimal:16',
        'dad_qt_vazaodiaout' => 'decimal:16',
        'dad_qt_vazaodianov' => 'decimal:16',
        'dad_qt_vazaodiadez' => 'decimal:16',
        'dad_qt_horasjan' => 'decimal:1',
        'dad_qt_horasfev' => 'decimal:1',
        'dad_qt_horasmar' => 'decimal:1',
        'dad_qt_horasabr' => 'decimal:1',
        'dad_qt_horasmai' => 'decimal:1',
        'dad_qt_horasjun' => 'decimal:1',
        'dad_qt_horasjul' => 'decimal:1',
        'dad_qt_horasago' => 'decimal:1',
        'dad_qt_horasset' => 'decimal:1',
        'dad_qt_horasout' => 'decimal:1',
        'dad_qt_horasnov' => 'decimal:1',
        'dad_qt_horasdez' => 'decimal:1',
        'dad_qt_diajan' => 'integer',
        'dad_qt_diafev' => 'integer',
        'dad_qt_diamar' => 'integer',
        'dad_qt_diaabr' => 'integer',
        'dad_qt_diamai' => 'integer',
        'dad_qt_diajun' => 'integer',
        'dad_qt_diajul' => 'integer',
        'dad_qt_diaago' => 'integer',
        'dad_qt_diaset' => 'integer',
        'dad_qt_diaout' => 'integer',
        'dad_qt_dianov' => 'integer',
        'dad_qt_diadez' => 'integer',
        'int_qt_vazaomaxima' => 'decimal:16',
        'int_qt_vazaomedia' => 'decimal:16',
        'int_qt_volumeanual' => 'decimal:16',
        'fin_tfn_cd' => 'integer',
        'fes_nu_profundidademediatanque' => 'decimal:16',
        'fes_nu_areatotaltanque' => 'decimal:16',
        'ttc_tcu_cd' => 'decimal:16',
        'fse_tes_cd' => 'integer',
        'fie_tps_cd' => 'integer',
        'fah_tah_cd' => 'integer',
        'fah_nu_potenciainstalada' => 'decimal:16',
        'fah_ic_aproveitamentofiodagua' => 'boolean',
        'fah_nu_areainundadana' => 'decimal:16',
        'fah_nu_volumena' => 'decimal:16',
        'fpe_tpe_cd' => 'integer',
        'fpe_cna_cd' => 'integer',
        'ius_nu_alturares' => 'decimal:16',
        'ius_nu_arearesmax' => 'decimal:16',
        'ius_nu_volumeres' => 'decimal:16',
        'ius_nu_coeficiente_retorno' => 'decimal:16',
        'ius_dt_finalconcessao' => 'date',
        'sir_tsi_cd' => 'integer',
        'sir_tct_cd' => 'integer',
        'sir_nu_areairrigada' => 'decimal:16',
        'fia_nu_populacaoatendida' => 'integer',
        'fea_nu_proporcaoaguapolpa' => 'integer',
        'foh_toh_cd' => 'integer',
        'fre_nu_areainundadana' => 'decimal:16',
        'fre_nu_volumena' => 'decimal:16',
        'fou_tou_cd' => 'integer',
        'hte_nu_quantidade' => 'integer',
        'tuc_tec_cd' => 'integer',
        'tuc_cd' => 'integer',
        'ftr_ar_totalempreendimento' => 'decimal:16',
        'esc_nu_producaopretendida' => 'integer',
        'esc_tet_cd' => 'integer',
        'cte_tsc_cd' => 'integer',
        'cte_tca_cd' => 'integer',
        'cte_nu_cabecas' => 'integer',
        'efl_nu_dbobruto' => 'decimal:16',
        'efl_nu_dbotratado' => 'decimal:16',
        'efl_nu_fosforobruto' => 'decimal:16',
        'efl_nu_fosforotratado' => 'decimal:16',
        'efl_nu_nitrogeniobruto' => 'decimal:16',
        'efl_nu_nitrogeniotratado' => 'decimal:16',
        'efl_nu_temperatura' => 'decimal:16',
        'efl_tte_cd' => 'integer',
        'itc_tum_cd' => 'integer',
        'itc_nu_producaoanual' => 'integer',
        'asb_dt_instalacao' => 'date',
        'asb_tnp_cd' => 'integer',
        'asb_nu_diametroperfuracao' => 'decimal:16',
        'asb_nu_diametrofiltro' => 'decimal:16',
        'asb_aqp_cd' => 'integer',
        'asb_nu_topo' => 'integer',
        'asb_nu_base' => 'decimal:16',
        'asb_tpn_cd' => 'integer',
        'abs_tca_cd' => 'integer',
        'asb_nu_profundidadefinal' => 'decimal:16',
        'asb_nu_alturabocatubo' => 'decimal:16',
        'asb_nu_cotaterreno' => 'integer',
        'tst_ttb_cd' => 'integer',
        'tst_ds_tempoduracao' => 'integer',
        'tst_nu_nd' => 'decimal:16',
        'tst_nu_ne' => 'decimal:16',
        'tst_vz_estabilizacao' => 'decimal:16',
        'tst_tmi_cd' => 'integer',
        'tst_nu_permeabilidade' => 'integer',
        'ama_dt_coleta' => 'date',
        'ama_dt_analise' => 'date',
        'ama_nu_condutividadeeletrica' => 'decimal:16',
        'ama_qt_temperatura' => 'decimal:16',
        'ama_qt_std' => 'decimal:16',
        'ama_qt_ph' => 'decimal:16',
        'ama_qt_coliformestotais' => 'decimal:16',
        'ama_qt_coliformesfecais' => 'integer',
        'ama_qt_bicarbonato' => 'decimal:16',
        'ama_qt_calcio' => 'decimal:16',
        'ama_qt_carbonato' => 'decimal:16',
        'ama_qt_cloreto' => 'decimal:16',
        'ama_qt_durezatotal' => 'decimal:16',
        'ama_qt_ferrototal' => 'decimal:16',
        'ama_qt_fluoretos' => 'decimal:16',
        'ama_qt_nitratos' => 'decimal:16',
        'ama_qt_nitritos' => 'decimal:16',
        'ama_qt_potassio' => 'decimal:16',
        'ama_qt_sodio' => 'decimal:16',
        'ama_qt_sulfato' => 'decimal:16',
        'ama_qt_magnesio' => 'decimal:16',
        'data_extracao' => 'datetime',
        'ing_cd_ottobacia_trecho' => 'integer',
        'ing_cd_comitefederal' => 'integer',
        'ing_cd_comiteestadual' => 'integer',
        'ing_cs_conama' => 'integer',
        'fir_nu_areatotalirrigada' => 'decimal:16',
    ];
}
