<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class HwStationReadingQa extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'hw_station_readings_qa';

    protected $fillable = [
        // Informações básicas da estação
        'station_code',
        'data_hora_dado',
        'data_ultima_alteracao', 
        'nivel_consistencia', 
        'num_medicao',
        'posicao_horizontal_coleta',
        'posicao_vertical_coleta',
        'profundidade_m',
        'choveu',
        
        // Parâmetros básicos (1-24) - valores e status
        '1_alcalinidade_total_mgl_caco3', '1_status',
        '2_carbono_organico_total_mgl', '2_status',
        '3_cloretos_mgl_cl', '3_status',
        '4_clorofila_ugl', '4_status',
        '5_coliformes_termo_tolerantes_ufc_100ml', '5_status',
        '6_condutividade_especifica_25oc_us_cm_a_25c', '6_status',
        '7_dbo_mgl_02', '7_status',
        '8_descarga_liquida_m3s', '8_status',
        '9_dqo_mgl_02', '9_status',
        '10_escherichiacoli_ufc_100ml', '10_status',
        '11_fitoplancton_quantitativo_celulas_100ml', '11_status',
        '12_fosforo_total_mgl', '12_status',
        '13_nitratos_mgl_n', '13_status',
        '14_nitrogenio_amoniacal_mgl', '14_status',
        '15_nitrogenio_total_mgl_n', '15_status',
        '16_ortofosfato_total_mgl_po4', '16_status',
        '17_od_mgl_02', '17_status',
        '18_ph', '18_status',
        '19_soldissolvidos_totais_mgl', '19_status',
        '20_solsuspensao_totais_mgl', '20_status',
        '21_temperatura_amostra_c', '21_status',
        '22_tempar_c', '22_status',
        '23_transparencia_m', '23_status',
        '24_turbidez_ntu', '24_status',
        
        // Parâmetros químicos (25-97) - valores e status
        '25_acidez_mgl_caco3', '25_status',
        '26_alcalinidade_co3_mgl', '26_status',
        '27_alcalinidade_hco3_mgl', '27_status',
        '28_alcalinidade_oh_mgl', '28_status',
        '29_aluminio_dissolvido_mgl', '29_status',
        '30_aluminio_mgl_al', '30_status',
        '31_amonia_nao_ionizavel_mgl_nh3', '31_status',
        '32_arsenio_mgl', '32_status',
        '33_bario_mgl_ba', '33_status',
        '34_berilio_mgl', '34_status',
        '35_bismuto_total_mgl', '35_status',
        '36_borodissolvido_mgl', '36_status',
        '37_boro_mgl_b', '37_status',
        '38_cadmio_mgl_cd', '38_status',
        '39_calcio_total_mgl', '39_status',
        '40_chumbo_mgl', '40_status',
        '41_cianeto_livre_mgl', '41_status',
        '42_cianetos_mgl_cn', '42_status',
        '43_cobalto_mgl_co', '43_status',
        '44_cobre_dissolvido_mgl', '44_status',
        '45_cobre_mgl_cu', '45_status',
        '46_coliformes_fecais_nmp_100ml', '46_status',
        '47_coliformes_totais_nmp_100ml', '47_status',
        '48_compostos_organo_clorados_mgl', '48_status',
        '49_compostos_organo_fosforados_mgl', '49_status',
        '50_condutivida_de_eletrica_us_cm_a_20c', '50_status',
        '51_cor_mg_pt_col', '51_status',
        '52_cromo_hexavalente_mgl', '52_status',
        '53_cromo_total_mgl_cr', '53_status',
        '54_cromo_trivalente_mgl', '54_status',
        '55_densidade_ciano_bacterias_cel_ml', '55_status',
        '56_detergentes_mgl_las', '56_status',
        '57_dureza_mgl_caco3', '57_status',
        '58_dureza_magnesio_mgl_mgco3', '58_status',
        '59_dureza_total_mgl', '59_status',
        '60_estanho_mgl', '60_status',
        '61_estreptococos_fecais_nmp_100ml', '61_status',
        '62_ferro_dissolvido_mgl', '62_status',
        '63_ferro_total_mgl', '63_status',
        '64_fluoretos_mgl', '64_status',
        '65_fosfato_total_mgl', '65_status',
        '66_hidrocarbonetos_mgl', '66_status',
        '67_indicefenois_mgl_c6h5oh', '67_status',
        '68_iqa', '68_status',
        '69_litio_mgl', '69_status',
        '70_magnesio_total_mgl', '70_status',
        '71_manganes_mgl', '71_status',
        '72_mercurio_mgl', '72_status',
        '73_niquel_mgl', '73_status',
        '74_nitritos_mgl', '74_status',
        '75_nitrogenio_organico_mgl', '75_status',
        '76_nitrogenio_total_kjeldahl_mgl', '76_status',
        '77_oleos_graxas_mgl', '77_status',
        '78_od_perc_saturacao', '78_status',
        '79_potassio_total_mgl', '79_status',
        '80_prata_mgl', '80_status',
        '81_parametro_profundidade_m', '81_status',
        '82_selenio_mgl', '82_status',
        '83_silicadissolvida_mgl', '83_status',
        '84_sodiototal_mgl', '84_status',
        '85_soldissolvidos_fixos_mgl_a_180c', '85_status',
        '86_soldissolvidos_volateis_mgl', '86_status',
        '87_sol_suspensao_fixos_mgl', '87_status',
        '88_sol_suspensao_volateis_mgl', '88_status',
        '89_solfixos_mgl', '89_status',
        '90_sol_sedimentaveis_mgl', '90_status',
        '91_sol_totais_mgl', '91_status',
        '92_sol_volateis_mgl', '92_status',
        '93_sulfatos_mgl', '93_status',
        '94_sulfetos_mgl', '94_status',
        '95_uranio_total_mgl', '95_status',
        '96_vanadio_mgl', '96_status',
        '97_zinco_mgl', '97_status',
        
        // Compostos orgânicos (98-135) - valores e status
        '98_1_1_dicloroeteno_mgl', '98_status',
        '99_1_2_dicloroetano_mgl', '99_status',
        '100_2_4_5_t_mgl', '100_status',
        '101_2_4_5_tp_mgl', '101_status',
        '102_2_4_6_triclorofenol_mgl', '102_status',
        '103_acido_2_4_diclorofenoxiacetico_mgl', '103_status',
        '104_aldrin_mgl', '104_status',
        '105_azinfosetil_mgl', '105_status',
        '106_benzeno_mgl', '106_status',
        '107_benzoapireno_mgl', '107_status',
        '108_bhc_mgl', '108_status',
        '109_bifenilaspolicloradas_mgl', '109_status',
        '110_carbaril_mgl', '110_status',
        '111_clordano_mgl', '111_status',
        '112_ddepp_mgl', '112_status',
        '113_ddt_mgl', '113_status',
        '114_demeton_mgl', '114_status',
        '115_diazinon_mgl', '115_status',
        '116_dieldrin_mgl', '116_status',
        '117_dodecaclorononacloro_mgl', '117_status',
        '118_dysystondisulfton_mgl', '118_status',
        '119_endossulfan_mgl', '119_status',
        '120_endrin_mgl', '120_status',
        '121_epoxidoheptacloro_mgl', '121_status',
        '122_ethion_mgl', '122_status',
        '123_gution_mgl', '123_status',
        '124_heptacloro_mgl', '124_status',
        '125_lindano_mgl', '125_status',
        '126_malation_mgl', '126_status',
        '127_metilparation_mgl', '127_status',
        '128_metoxicloro_mgl', '128_status',
        '129_paration_mgl', '129_status',
        '130_pentaclorofenol_mgl', '130_status',
        '131_phosdrin_mgl', '131_status',
        '132_tetra_cloreto_carbono_mgl', '132_status',
        '133_tetra_cloro_eteno_mgl', '133_status',
        '134_toxafeno_mgl', '134_status',
        '135_tricloro_eteno_mgl', '135_status',
        
        // Parâmetros biológicos (136-147) - valores e status
        '136_algas_n_upa_ml', '136_status',
        '137_amoniaco_mgl', '137_status',
        '138_bacterias_heterotroficas_ufc_ml', '138_status',
        '139_cloro_residual_mgl', '139_status',
        '140_colifagos_nmp_100ml', '140_status',
        '141_contagem_bacterias_placa_ufc_ml', '141_status',
        '142_entero_bacterias_patogenicas_n_org_ml', '142_status',
        '143_fungos_ufc_ml', '143_status',
        '144_nitrogenio_albuminoide_mgl', '144_status',
        '145_protozoarios_n_org_ml', '145_status',
        '146_salmonelas_nmp_ml', '146_status',
        '147_zooplanctontotal_n_org_ml', '147_status',
    ];

    protected $casts = [
        'data_hora_dado' => 'datetime',
        'data_ultima_alteracao' => 'datetime',
        'choveu' => 'boolean',
        'num_medicao' => 'integer',
        'posicao_horizontal_coleta' => 'integer',
        'posicao_vertical_coleta' => 'integer',
        'station_code' => 'integer',
    ];

    /**
     * Relationship with station
     */
    public function station()
    {
        return $this->belongsTo(HwInventoryStation::class, 'station_code', 'station_code');
    }
}